# Generated by Django 5.1.1 on 2026-06-26 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_alter_location_options_and_more'),
        ('blog', '0005_post_image'),
    ]

    operations = [
    ]
